'use client';
import ActionIcon from './ActionIcon';


import { ChangeEvent, useRef, useState } from 'react';
import { fetchSupabaseFunction, getSupabaseBrowserClient } from '../lib/supabase/browser';

type ClientRow = Record<string, unknown> & { assigned_id?: number; company_name?: string; country?: { name?: string }; fee_classification?: { description?: string } };
type Props = { search: string; onComplete: (message: string) => void; onError: (message: string) => void; onRefresh: () => void };
const headers = ['company_name','email','phone','client_type','address','country_id','fee_classification_id','notes','status'];
const csvCell = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`;
const save = (name: string, type: string, content: string) => { const url=URL.createObjectURL(new Blob([content],{type})); const link=document.createElement('a'); link.href=url; link.download=name; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(()=>URL.revokeObjectURL(url),1000); };

async function sessionToken() { const supabase=getSupabaseBrowserClient(); const {data:{session}}=supabase?await supabase.auth.getSession():{data:{session:null}}; if(!session) throw Error('Please sign in.'); return session.access_token; }
async function allClients(token: string, search: string) { const rows:ClientRow[]=[]; let page=1,total=0; do { const params=new URLSearchParams({page:String(page),page_size:'100'}); if(search.trim())params.set('search',search.trim()); const response=await fetchSupabaseFunction(`clients?${params}`,{headers:{Authorization:`Bearer ${token}`}}); const body=await response.json().catch(()=>({})); if(!response.ok)throw Error(body.error||'Unable to export clients.'); rows.push(...(body.data||[])); total=body.total||0; page+=1; } while(rows.length<total); return rows; }
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(char===','&&!quoted){row.push(value.trim());value=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(value.trim());if(row.some(Boolean))rows.push(row);row=[];value=''}else value+=char}row.push(value.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)throw Error('CSV must contain a header and at least one data row.');const names=rows[0].map(item=>item.toLowerCase());for(const required of ['company_name','email','phone','client_type','address','country_id','status'])if(!names.includes(required))throw Error(`CSV is missing required column: ${required}`);return rows.slice(1).map((cells,index)=>{const item:Record<string,string|null>={};names.forEach((name,column)=>{if(headers.includes(name))item[name]=cells[column]?.trim()||null});if(!item.company_name||!item.email)throw Error(`Row ${index+2} is missing company name or email.`);return item});}

export default function ClientDataActions({search,onComplete,onError,onRefresh}:Props){const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState('');
 const exportJson=async()=>{try{setBusy('export');const rows=await allClients(await sessionToken(),search);save(`aipt-clients-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify(rows,null,2));onComplete(`${rows.length} clients exported.`)}catch(cause){onError(cause instanceof Error?cause.message:'Export failed.')}finally{setBusy('')}};
 const exportExcel=async()=>{try{setBusy('excel');const rows=await allClients(await sessionToken(),search);const columns=['assigned_id','company_name','fee_classification','email','phone','client_type','address','country','notes','status'];const lines=[columns.map(csvCell).join(','),...rows.map(row=>columns.map(column=>csvCell(column==='country'?row.country?.name:column==='fee_classification'?row.fee_classification?.description:row[column])).join(','))];save(`aipt-clients-${new Date().toISOString().slice(0,10)}.csv`,'text/csv;charset=utf-8','\uFEFF'+lines.join('\r\n'));onComplete(`${rows.length} clients downloaded for Excel.`)}catch(cause){onError(cause instanceof Error?cause.message:'Excel download failed.')}finally{setBusy('')}};
 const importCsv=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>2*1024*1024){onError('CSV import must be 2MB or smaller.');return}try{setBusy('import');const rows=parseCsv(await file.text());if(rows.length>500)throw Error('A single import is limited to 500 clients.');const token=await sessionToken();const response=await fetchSupabaseFunction('clients?mode=import',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({rows})});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body.error||'Import failed.');onComplete(`${body.imported||rows.length} clients imported successfully.`);onRefresh()}catch(cause){onError(cause instanceof Error?cause.message:'Import failed.')}finally{setBusy('')}};
 return <div className="client-data-actions"><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={importCsv}/><button type="button" onClick={()=>input.current?.click()} disabled={Boolean(busy)} data-action="import" title="Import"><ActionIcon name="import" /><span className="aipt-action-label">{busy==='import'?'Importing...':'Import'}</span></button><button type="button" onClick={()=>void exportJson()} disabled={Boolean(busy)} data-action="export" title="Export"><ActionIcon name="export" /><span className="aipt-action-label">{busy==='export'?'Exporting...':'Export'}</span></button><button type="button" onClick={()=>void exportExcel()} disabled={Boolean(busy)} data-action="export" title="Excel"><ActionIcon name="export" /><span className="aipt-action-label">{busy==='excel'?'Preparing...':'Excel'}</span></button></div>;
}
