'use client';

import { useEffect, useMemo, useState } from 'react';
import { fetchSupabaseFunction, getSupabaseBrowserClient } from '../../../src/lib/supabase/browser';

type Notification = { id: string; notification_date: string; description: string; document_name: string | null; document_size: number | null; countries: Array<{ country: { name: string; abbreviation: string; flag_url: string } }> };
const date = (value: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
async function loadNotifications() { const supabase = getSupabaseBrowserClient(); if (!supabase) throw Error('Supabase is not configured.'); const { data: { session } } = await supabase.auth.getSession(); if (!session) throw Error('Please sign in.'); const response = await fetchSupabaseFunction('notifications', { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw Error(body.error || 'Unable to load notifications.'); return body as Notification[]; }

export default function ClientNotificationsPage() { const [items, setItems] = useState<Notification[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); useEffect(() => { void loadNotifications().then(setItems).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load notifications.')); }, []); const visible = useMemo(() => items.filter((item) => `${item.description} ${item.document_name || ''} ${item.countries.map((entry) => entry.country.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [items, query]); return <section className="client-page"><div className="client-heading"><div><h1>Notifications</h1><p>Stay up to date with changes and documents related to your portfolio.</p></div></div>{error && <p className="client-error">{error}</p>}<div className="client-toolbar"><label>⌕ <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notifications..." /></label><span className="result-count">{visible.length} notifications</span></div><div className="client-panel"><div className="panel-title"><h2>Portfolio Notifications</h2><span>Latest first</span></div><div className="notification-list">{visible.map((item) => <article className="client-notification" key={item.id}><span className="notification-dot">•</span><div><strong>{item.description}</strong><p>{date(item.notification_date)} · {item.countries.map((entry) => entry.country.name).join(', ') || 'Portfolio update'}</p></div><div className="notification-document">{item.document_name ? <><b>PDF</b><span>{item.document_name}<small>{item.document_size ? `${Math.round(item.document_size / 1024)} KB` : 'Document'}</small></span></> : <span>No document attached</span>}</div></article>)}{!visible.length && <p className="client-empty">No notifications for your portfolio.</p>}</div></div></section>; }
