-- Clients are the source of truth for the Admin Client page. The visible ID is
-- numeric and generated by Postgres, so concurrent creates cannot reuse an ID.
create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  assigned_id bigint generated by default as identity,
  company_name varchar(255) not null check (char_length(trim(company_name)) between 2 and 255),
  fee_classification_id uuid references public.fee_classifications(id),
  email varchar(320) not null check (char_length(trim(email)) between 3 and 320),
  phone varchar(80) not null check (char_length(trim(phone)) between 3 and 80),
  client_type varchar(40) not null check (client_type in ('Corporate', 'Law Firm', 'Consultant', 'Individual')),
  address text not null check (char_length(trim(address)) between 3 and 2000),
  country_id uuid not null references public.countries(id),
  notes text not null default '' check (char_length(notes) <= 4000),
  status varchar(20) not null default 'Active' check (status in ('Active', 'Inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists clients_assigned_id_unique on public.clients (assigned_id);
create unique index if not exists clients_company_name_active_unique on public.clients (lower(company_name)) where deleted_at is null;
create index if not exists clients_active_list_index on public.clients (assigned_id) where deleted_at is null;
create index if not exists clients_country_active_index on public.clients (country_id) where deleted_at is null;
drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at before update on public.clients for each row execute procedure public.set_updated_at();
alter table public.clients enable row level security;
create policy "authenticated users can read active clients" on public.clients for select to authenticated using (deleted_at is null);

-- Projects are the related applications/matters shown from a client record.
-- Class is nullable because it applies to Trademark (required by API) and
-- Copyright (optional), but not the other service types.
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id),
  service_id uuid not null references public.services(id),
  procedure_id uuid not null references public.procedures(id),
  country_id uuid not null references public.countries(id),
  matter_type varchar(20) not null check (matter_type in ('trademark', 'patent', 'design', 'copyright', 'other')),
  matter_date date not null,
  aipt_ref_no varchar(120) not null check (char_length(trim(aipt_ref_no)) between 1 and 120),
  client_ref_no varchar(120) not null check (char_length(trim(client_ref_no)) between 1 and 120),
  project_name varchar(255) not null check (char_length(trim(project_name)) between 2 and 255),
  class_number smallint check (class_number between 1 and 50),
  filing_number varchar(120),
  filing_date date,
  acceptance_number varchar(120),
  acceptance_date date,
  register_number varchar(120),
  registered_date date,
  renewal_date date,
  applicant varchar(255) not null check (char_length(trim(applicant)) between 2 and 255),
  status varchar(64) not null check (char_length(trim(status)) between 2 and 64),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists projects_client_active_index on public.projects (client_id, matter_date desc) where deleted_at is null;
create index if not exists projects_client_type_active_index on public.projects (client_id, matter_type, matter_date desc) where deleted_at is null;
create index if not exists projects_service_active_index on public.projects (service_id, matter_date desc) where deleted_at is null;
create index if not exists projects_procedure_active_index on public.projects (procedure_id) where deleted_at is null;
create index if not exists projects_country_active_index on public.projects (country_id) where deleted_at is null;
drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects for each row execute procedure public.set_updated_at();

-- The Edge Function performs friendly validation. This trigger keeps the same
-- core service/procedure and class rules true for any future direct write path.
create or replace function public.validate_project_integrity()
returns trigger
language plpgsql
as $$
declare
  procedure_service_id uuid;
begin
  select service_id
    into procedure_service_id
    from public.procedures
   where id = new.procedure_id
     and deleted_at is null;

  if procedure_service_id is null or procedure_service_id <> new.service_id then
    raise exception 'The selected procedure must belong to the selected service.' using errcode = '23514';
  end if;

  if new.matter_type = 'trademark' and new.class_number is null then
    raise exception 'Class is required for Trademark matters.' using errcode = '23514';
  end if;

  if new.matter_type not in ('trademark', 'copyright') and new.class_number is not null then
    raise exception 'Class applies only to Trademark or Copyright matters.' using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists projects_validate_integrity on public.projects;
create trigger projects_validate_integrity
  before insert or update of service_id, procedure_id, matter_type, class_number
  on public.projects
  for each row execute procedure public.validate_project_integrity();

alter table public.projects enable row level security;
create policy "authenticated users can read active projects" on public.projects for select to authenticated using (deleted_at is null);
