'use client';
import { uploadCompanyLogo, validateLogo } from '../../src/lib/logo-upload';
import ActionIcon from '../../src/components/ActionIcon';


import { FormEvent, useEffect, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { fetchSupabaseFunction, getSupabaseBrowserClient } from '../../src/lib/supabase/browser';

export default function AccountPage() {
  const router = useRouter();
  const isClient = usePathname().startsWith('/client-dashboard');
  const [email, setEmail] = useState(''); const [fullName, setFullName] = useState(''); const [company, setCompany] = useState(''); const [address, setAddress] = useState(''); const [logo, setLogo] = useState('');
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { const load = async () => { const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { data: { session } } = await supabase.auth.getSession(); if (!session) { router.replace('/login'); return; } const response = await fetchSupabaseFunction('account', { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error || 'Unable to load account information.'); return; } setEmail(body.email || ''); setFullName(body.full_name || ''); setCompany(body.company_name || ''); setAddress(body.address || ''); setLogo(body.logo_url || ''); }; void load(); }, [router]);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const supabase = getSupabaseBrowserClient(); if (!supabase) throw Error('Supabase is not configured.'); const { data: { session } } = await supabase.auth.getSession(); if (!session) throw Error('Please sign in.'); const logoKey = logoFile ? await uploadCompanyLogo(logoFile, session.access_token) : undefined; const response = await fetchSupabaseFunction('account', { method: 'PUT', headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ full_name: fullName, company_name: company, address, logo_key: logoKey }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw Error(body.error || 'Unable to update account.'); setFullName(body.full_name || fullName); setCompany(body.company_name || company); setAddress(body.address || address); setLogo(body.logo_url || logo); setLogoFile(null); setNotice('Information updated.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update account.'); } finally { setSaving(false); } };
  const chooseLogo = (file: File | null) => { setLogoFile(null); if (!file) return; try { validateLogo(file); setLogoFile(file); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Invalid logo.'); } };
  return <main className="account-page"><section className="account-modal" aria-labelledby="account-title"><header><div><span>{isClient ? "CLIENT ACCOUNT" : "ADMIN ACCOUNT"}</span><h1 id="account-title">Account settings</h1><p>Manage your profile and organization details.</p></div><button type="button" aria-label="Close" onClick={() => router.back()}>×</button></header><form onSubmit={save}><div className="account-logo-field">{logo ? <img src={logo} alt="Current organization logo" /> : <b>{company.slice(0, 1).toUpperCase() || 'A'}</b>}<label>Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => chooseLogo(event.target.files?.[0] ?? null)} /><small>PNG, JPG, or WEBP · 500 MB maximum</small>{logoFile && <small>{logoFile.name} selected</small>}</label></div><div className="account-form-grid"><label>Full name<input value={fullName} onChange={(event) => setFullName(event.target.value)} required /></label><label>Company<input value={company} onChange={(event) => setCompany(event.target.value)} required /></label><label>Email<input value={email} readOnly aria-readonly="true" /></label><label className="account-address">Address<textarea value={address} onChange={(event) => setAddress(event.target.value)} rows={3} minLength={3} required /></label></div>{error && <p className="client-error" role="alert">{error}</p>}{notice && <p className="client-notice" role="status">{notice}</p>}<footer><button type="button" onClick={() => router.back()} disabled={saving} data-action="cancel" title="Cancel"><ActionIcon name="cancel" /><span className="aipt-action-label">Cancel</span></button><button className="account-save" disabled={saving} data-action="update" title="Save information"><ActionIcon name="update" /><span className="aipt-action-label">{saving ? 'Saving...' : 'Save information'}</span></button></footer></form></section></main>;
}